### ISSUE TITLE
production server instance

### ISSUE THREAD

**Issue by djpnewton** [zap-me/zapm_server#19]
We will need a production server instance at merchant.zap.me

We will run it in a caprover docker container (see https://github.com/djpnewton/acuerdo-kyc/blob/master/captain-definition)

@eoliveros you can probably install caprover into one of your acuerdo servers and then just use a merchant virtual subdomain or let me know if you want me to provision a new VM specifically for us to test caprover deployments (probly better to do that actually)

**Comment by eoliveros** [comment]
I've not dealt with docker. better to get a new vm.

**Comment by djpnewton** [comment]
added at caprover.acuerdo.dev

**Comment by djpnewton** [comment]
Can you check out the new VM, we need to get this deployed this week

**Comment by eoliveros** [comment]
cant connect to this server.
$ ssh caprover.acuerdo.dev
ssh: Could not resolve hostname caprover.acuerdo.dev: Temporary failure in name resolution
eoliveros@DevIntServer:~$

cant browse to it either.

**Comment by djpnewton** [comment]
try now

**Comment by eoliveros** [comment]
can ssh. but can't get into the browser. I think im getting firewalled from work. getting something in port 80 with the server ip address but not https or port 3000.

**Comment by djpnewton** [comment]
use the CLI app to set it up: https://caprover.com/docs/get-started.html#step-3-install-caprover-cli

**Comment by eoliveros** [comment]
installed the server as per the doc.

But when attempting to deploy:
```
caprover deploy


------------
CapRover CLI has recently been refactored. Please report potential bugs here: https://github.com/caprover/caprover-cli/issues
------------


Preparing deployment to CapRover...

? select the CapRover machine name you want to deploy to: captain-01
Ensuring authentication...
? select the app name you want to deploy to: (Use arrow keys)
❯ -- CANCEL --
root@caprover
```
its not returning anything in the list.

It appears that I need to create the app first. But to do that, I need to login via browser and then create the app so I could perform the next step which is to deploy. Can't create the app because having dificulty getting out of the network.

**Comment by eoliveros** [comment]
created the app name from the browser "test-zapm-server".
git clone the server locally:
```
root@caprover:~/git/zapm_server# ls -la
total 128
drwxr-xr-x 5 root root  4096 Jun 22 05:23 .
drwxr-xr-x 3 root root  4096 Jun 22 04:55 ..
drwxr-xr-x 8 root root  4096 Jun 22 05:08 .git
-rw-r--r-- 1 root root  1225 Jun 22 04:55 .gitignore
-rw-r--r-- 1 root root  1063 Jun 22 04:55 LICENSE
-rw-r--r-- 1 root root    20 Jun 22 04:55 Procfile
-rw-r--r-- 1 root root  2375 Jun 22 04:55 addresswatcher.py
-rw-r--r-- 1 root root  1735 Jun 22 04:55 admin.py
-rw-r--r-- 1 root root 15296 Jun 22 05:03 app.py
-rw-r--r-- 1 root root  2063 Jun 22 04:55 app_core.py
-rw-r--r-- 1 root root  2718 Jun 22 04:55 bnz_ib4b.py
-rw-r--r-- 1 root root   492 Jun 22 05:20 captain-definition
-rw-r--r-- 1 root root   928 Jun 22 04:55 config.py
-rw-r--r-- 1 root root 29275 Jun 22 05:03 models.py
-rw-r--r-- 1 root root   287 Jun 22 04:55 requirements.txt
-rw-r--r-- 1 root root   287 Jun 22 04:57 requirements2.txt
drwxr-xr-x 2 root root  4096 Jun 22 04:55 static
drwxr-xr-x 4 root root  4096 Jun 22 04:55 templates
-rw-r--r-- 1 root root  9579 Jun 22 04:55 test_api.py
-rw-r--r-- 1 root root  2787 Jun 22 05:03 utils.py
root@caprover:~/git/zapm_server#
```

create captain-definition file. i think i had to commit the captain-definition file in git. otherwise it doesn't appear to see it.


but its now deploying, still fail to load though.
```
2020-06-22T05:44:01.984399410Z [__main__ ERROR] SETTLEMENT_ADDRESS does not exist
2020-06-22T05:44:09.329048624Z [__main__ ERROR] SETTLEMENT_ADDRESS does not exist
2020-06-22T05:44:16.623293310Z [__main__ ERROR] SETTLEMENT_ADDRESS does not exist
```

looks like those are config things from within the app.

to make changes, you also need to delete the app as well as the images.


trying again

**Comment by eoliveros** [comment]
adding the following in the config.py
```
SETTLEMENT_ADDRESS = ""
SENDER_BANK_ACCOUNT = ""
SENDER_NAME = ""
```

**Comment by eoliveros** [comment]
the above needed to be committed for it to take effect. trying again.

**Comment by eoliveros** [comment]
manage the bring the site up.... but cant register. erroring:
```
docker logs srv-captain--test-zapm-server.1.cw1zz4ip3zxt137xe7qeupw4n
/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/sqltypes.py:667: SAWarning: Dialect sqlite+pysqlite does *not* support Decimal objects natively, and SQLAlchemy must convert from floating point - rounding errors and other issues may occur. Please consider storing Decimal numbers as strings or integers on this platform for lossless storage.
  "storage." % (dialect.name, dialect.driver)
[2020-06-22 23:06:49,890] ERROR in app: Exception on /admin/register/ [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask_security/decorators.py", line 225, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask_security/views.py", line 117, in register
    user = register_user(**form.to_dict())
  File "/usr/local/lib/python3.7/site-packages/flask_security/registerable.py", line 41, in register_user
    user=user, confirmation_link=confirmation_link)
  File "/usr/local/lib/python3.7/site-packages/flask_security/utils.py", line 341, in send_mail
    mail.send(msg)
  File "/usr/local/lib/python3.7/site-packages/flask_mail_sendgrid.py", line 88, in send
    res = self.sg.client.mail.send.post(request_body=mail.get())
  File "/usr/local/lib/python3.7/site-packages/python_http_client/client.py", line 262, in http_request
    self._make_request(opener, request, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/python_http_client/client.py", line 178, in _make_request
    raise exc
python_http_client.exceptions.UnauthorizedError: HTTP Error 401: Unauthorized
```

trying to figure out whats causing this.

**Comment by eoliveros** [comment]
hmmm sendgrid?, i thought I included it in the captain-definition. removing it and setting it in the apps config instead.

**Comment by eoliveros** [comment]
its up.
from the gui side needed to do the following:
```
create the app.
enable https
force https.
config the no_waves environment as well as the sendgrid api key
```
once the above is done:
```
first time:
caprover deploy -c captain-definition --caproverName captain-01 -a test-zapm-server -b feature-20200617_merchantrate

re-deployment:
caprover deploy --default
```

the above will deploy the app but data loses each time its redeploy.

**Comment by djpnewton** [comment]
> hmmm sendgrid?, i thought I included it in the captain-definition. removing it and setting it in the apps config instead.

dont put settings in the code (captain-definition) we dont want sensitive data like that in git

**Comment by djpnewton** [comment]
this app does not have a "no_waves" environment variable

**Comment by eoliveros** [comment]
> > hmmm sendgrid?, i thought I included it in the captain-definition. removing it and setting it in the apps config instead.
> 
> dont put settings in the code (captain-definition) we dont want sensitive data like that in git

yeah i took those out before.

**Comment by djpnewton** [comment]
I have deployed to merchant.zap.me, it will automatically deploy using the captain-definition file on the production branch of this repo

@eoliveros  I need you to test the features:

1. make sure you have the latest version of the app 1.2.7 (https://play.google.com/store/apps/details?id=me.zap.merchantapp)
2. Create an account at merchant.zap.me
3. Connect the app
4. Test notifications of received transactions
5. Test sending zap
6. Test settling zap
7. Test transaction history on the app and on the web portal

**Comment by eoliveros** [comment]
> I have deployed to merchant.zap.me, it will automatically deploy using the captain-definition file on the production branch of this repo
> 
> @eoliveros I need you to test the features:
> 
> 1. make sure you have the latest version of the app 1.2.7 (https://play.google.com/store/apps/details?id=me.zap.merchantapp)
> 2. Create an account at merchant.zap.me
> 3. Connect the app
> 4. Test notifications of received transactions
> 5. Test sending zap
> 6. Test settling zap
> 7. Test transaction history on the app and on the web portal

This is failing on registering a new account
```
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

**Comment by djpnewton** [comment]
Can you test again with the latest version of the app (1.2.10) and mainnet.

Also make my work email account an admin (log on the server and run `app.py add_role <EMAIL> admin`)

**Comment by eoliveros** [comment]
where is this instance of production zapm_server is installed? and please give me access to it if i dont already have one.

tried ssh'ing to the merchant.zap.me dirrectly using root and eoliveros but it looks like i dont have my public key on it.

**Comment by eoliveros** [comment]
also just re-downloaded from google apps, the app is still on Version 1.2.7 build 32
