### ISSUE TITLE
Show NZD value of transactions in MerchantTx table

### ISSUE THREAD

**Issue by djpnewton** [zap-me/zapm_server#20]
1. add 'amount_nzd' column to table
2. convert 'amount' to 'amount_nzd' when creating MerchantTx table items using merchant rate
3. display NZD amount to merchant

**Comment by eoliveros** [comment]
need to get a copy of the testnet zap app so i could send/receive.

Do you have a copy of the testnet version?

**Comment by djpnewton** [comment]
just use the merchant app on another device

**Comment by eoliveros** [comment]
did a push to my repo.

when the "Update" is pressed. it appears to look at user.merchant_rate and if it exists use it as the rate. if not, use the app.config. Based on the result for the rate, it will then insert the equivalent amount in NZ dollars into the column amount_nzd. Also records the rate that it is in the merchant_tx table. So we could track down what the rate that was applied.

**Comment by djpnewton** [comment]
fixed in #21
