### ISSUE TITLE
get server url from api key QR code

### ISSUE THREAD

**Issue by djpnewton** [zap-me/zapm_server#22]

**Comment by djpnewton** [comment]
@eoliveros can you put a new "server" parameter in the qr code https://github.com/zap-me/zapm_server/blob/80fa3260a3dc3ca490bcdac0c20912aaa064b186/models.py#L728

you can probably just use the flask request object to get the url (https://flask.palletsprojects.com/en/1.1.x/api/#flask.Request.path)

**Comment by eoliveros** [comment]
> @eoliveros can you put a new "server" parameter in the qr code
> 
> https://github.com/zap-me/zapm_server/blob/80fa3260a3dc3ca490bcdac0c20912aaa064b186/models.py#L728
> 
> you can probably just use the flask request object to get the url (https://flask.palletsprojects.com/en/1.1.x/api/#flask.Request.path)

you mean adding a variable called "server_url"?
also adding the result of the root_url to server_url variable?

**Comment by djpnewton** [comment]
no a parameter called "server" (shorter is better for qr codes)

dont just use the whole root_url, you will need to use a python library to parse the url and just extract the scheme and domain (eg https://example.com)

**Comment by eoliveros** [comment]
i used urllib.parse. returns the scheme and netloc but the netloc includes the port as well. so i used split and returned everything before the ":".

pushing to a new branch.

**Comment by djpnewton** [comment]
#24
