### ISSUE TITLE
show settlement address balance

### ISSUE THREAD

**Issue by djpnewton** [zap-me/zapm_server#25]
and show settlement address/balance to finance role

**Comment by eoliveros** [comment]
test is currently down. i think it maybe something to do with the fact that ive got another container running in the same port.

**Comment by eoliveros** [comment]
settlement address is the a wallet_address that where the zap is coming from/the wallet address that the finance team had setup?

**Comment by djpnewton** [comment]
settlement address is in `app.config["SETTLEMENT_ADDRESS"]`

in `before_request_func()` you should add some code like:

```
# not real code
if current_user.is_admin():
  current_user.settlement_wallet_balance = get_update_balance(app.config["SETTLEMENT_ADDRESS"])
```

then in the `my_master.html` template you can show the settlement address balance
